# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2.1

orbs:
  gradle: circleci/gradle@1.0.11

executors:
  java_8:
    docker:
      - image: circleci/openjdk:8-jdk
        environment:
          _JAVA_OPTIONS: -Xmx1025m
          TERM: dumb

workflows:
  version: 2.1
  build:
    jobs:
      - gradle/run:
          name: assemble
          executor: java_8
          command: build
          context: global
          filters:
            branches:
              ignore:
                - /release/.*/

  release:
    jobs:
      - gradle/run:
          name: assemble
          executor: java_8
          command: build
          context: global
          filters:
            branches:
              only:
                - /release/.*/
